---
- name: Run role
  hosts: all
  become: true
  any_errors_fatal: true

  vars:
    postgresql_initdb_locales: 'C.UTF-8'

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: ansible-apps_postgresql
